### ISSUE TITLE
Type Error while loading the module

### ISSUE THREAD

**Issue by SpinachXPasta** [evaneldemachki/deltaflow#1]
**So, I didn't do a pip install rather I did a git clone to run this,**

~/Desktop/deltaflow/deltaflow/fs.py in DeltaIO()
     13 # Chunk reader & writer for delta files
     14 class DeltaIO: # masks each block as a seperate file
---> 15     def __init__(self, obj: BinaryIO(), chunks: List[int]):
     16         self.obj = obj
     17         self.chunks = chunks

~/opt/anaconda3/envs/tf/lib/python3.6/typing.py in __new__(cls, *args, **kwds)
   1229             raise TypeError("Type Generic cannot be instantiated; "
   1230                             "it can be used only as a base class")
-> 1231         return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
   1232 
   1233 

~/opt/anaconda3/envs/tf/lib/python3.6/typing.py in _generic_new(base_cls, cls, *args, **kwds)
   1186             return base_cls.__new__(cls)
   1187         else:
-> 1188             return base_cls.__new__(cls, *args, **kwds)
   1189     else:
   1190         origin = cls._gorg

TypeError: Can't instantiate abstract class BinaryIO with abstract methods __enter__, __exit__, close, closed, fileno, flush, isatty, mode, name, read, readable, readline, readlines, seek, seekable, tell, truncate, writable, write, writelines

**I fixed this by replacing in fs.py** 

`def __init__(self, obj: BinaryIO(), chunks: List[int]):`

with 

`def __init__(self, obj: BinaryIO, chunks: List[int]):`

I don't know if this is a major issue

**Comment by evaneldemachki** [comment]
@siddharthapachhai fixed this in last commit, thanks!
