### ISSUE TITLE
FileExistsError on delta flow.touch

### ISSUE THREAD

**Issue by SpinachXPasta** [evaneldemachki/deltaflow#2]
FileExistsError                           Traceback (most recent call last)
<ipython-input-3-60a6d083a58e> in <module>
----> 1 deltaflow.touch()

~/Desktop/deltaflow/deltaflow/api.py in touch(path)
     15 def touch(path: str = os.getcwd()) -> None:
     16     core_path = os.path.join(path, '.deltaflow')
---> 17     os.mkdir(core_path)
     18 
     19     orig_path = os.path.join(core_path, 'origins')

FileExistsError: [Errno 17] File exists: '/Users/**/Desktop/deltaflow/.deltaflow'

**Once touch is run, the os.mkdir fails if touch is run again. Consider putting in exceptions or a check statement to see if file already exists.**

**Comment by evaneldemachki** [comment]
@siddharthapachhai Thanks! Fixed this in last commit
